#!/bin/bash
#==================================================================================================
#
#  Commit test script for the Blaze library
#
#  Copyright (C) 2013 Klaus Iglberger - All Rights Reserved
#
#  This file is part of the Blaze library. You can redistribute it and/or modify it under
#  the terms of the New (Revised) BSD License. Redistribution and use in source and binary
#  forms, with or without modification, are permitted provided that the following conditions
#  are met:
#
#  1. Redistributions of source code must retain the above copyright notice, this list of
#     conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright notice, this list
#     of conditions and the following disclaimer in the documentation and/or other materials
#     provided with the distribution.
#  3. Neither the names of the Blaze development group nor the names of its contributors
#     may be used to endorse or promote products derived from this software without specific
#     prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
#  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
#  SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
#  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
#  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
#  DAMAGE.
#
#==================================================================================================


# Environment configuration
SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BLAZE_PATH=$SCRIPT_PATH/../../blaze
BLAZETEST_PATH=$BLAZE_PATH/blazetest
BLAZEMARK_PATH=$BLAZE_PATH/blazemark




#==================================================================================================
# Compilation of the Blaze library
#==================================================================================================

echo
echo "==================================================================================================="
echo "= Compilation of the Blaze library"
echo "==================================================================================================="
echo

make -f $BLAZE_PATH/Makefile clean
make -f $BLAZE_PATH/Makefile
if [ $? != 0 ]; then echo " Error during compilation of the Blaze library"; exit 1; fi




#==================================================================================================
# Compilation of the Blaze test suite
#==================================================================================================

echo
echo "==================================================================================================="
echo "= Compilation of the Blaze test suite"
echo "==================================================================================================="
echo

make -f $BLAZETEST_PATH/Makefile clean
make -f $BLAZETEST_PATH/Makefile
if [ $? != 0 ]; then echo " Error during compilation of the Blaze test suite"; exit 1; fi




#==================================================================================================
# Execution of the Blaze test suite
#==================================================================================================

echo
echo "==================================================================================================="
echo "= Execution of the Blaze test suite"
echo "==================================================================================================="
echo

$BLAZETEST_PATH/run
if [ $? != 0 ]; then echo " Error during execution of the Blaze test suite"; exit 1; fi




#==================================================================================================
# Compilation of the Blaze benchmark suite
#==================================================================================================

echo
echo "==================================================================================================="
echo "= Compilation of the Blaze benchmark suite"
echo "==================================================================================================="
echo

./blazemark
if [ $? != 0 ]; then echo " Error during compilation of the Blaze benchmark suite"; exit 1; fi




#==================================================================================================
# Finishing the commit test
#==================================================================================================

echo
echo " Commit test succeeded!"
echo
