#!/bin/bash
#==================================================================================================
#
#  Release script for the Blaze library
#
#  Copyright (C) 2013 Klaus Iglberger - All Rights Reserved
#
#  This file is part of the Blaze library. You can redistribute it and/or modify it under
#  the terms of the New (Revised) BSD License. Redistribution and use in source and binary
#  forms, with or without modification, are permitted provided that the following conditions
#  are met:
#
#  1. Redistributions of source code must retain the above copyright notice, this list of
#     conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright notice, this list
#     of conditions and the following disclaimer in the documentation and/or other materials
#     provided with the distribution.
#  3. Neither the names of the Blaze development group nor the names of its contributors
#     may be used to endorse or promote products derived from this software without specific
#     prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
#  EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
#  SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
#  BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
#  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
#  DAMAGE.
#
#==================================================================================================


# Release information
MAJOR=1
MINOR=4




#==================================================================================================
# Setup of the two release archives
#==================================================================================================

mkdir blaze-$MAJOR.$MINOR
mkdir blaze-docu-$MAJOR.$MINOR
git clone http://code.google.com/p/blaze-lib ./blaze-$MAJOR.$MINOR
cd blaze-$MAJOR.$MINOR
rm -rf .git
find * -type f -iname ".gitignore" -exec rm -f {} \;
./configure
make doc
cp -r doc/html/* ../blaze-docu-$MAJOR.$MINOR
cd ..
tar czf blaze-$MAJOR.$MINOR.tar.gz ./blaze-$MAJOR.$MINOR
tar czf blaze-docu-$MAJOR.$MINOR.tar.gz ./blaze-docu-$MAJOR.$MINOR
rm -rf blaze-$MAJOR.$MINOR blaze-docu-$MAJOR.$MINOR
