#!/bin/bash
#==================================================================================================
#
#  Release script for the Blaze library
#
#  Copyright (C) 2011 Klaus Iglberger - All Rights Reserved
#
#  This file is part of the Blaze library. This library is free software; you can redistribute
#  it and/or modify it under the terms of the GNU General Public License as published by the
#  Free Software Foundation; either version 3, or (at your option) any later version.
#
#  This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
#  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#  See the GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License along with a special
#  exception for linking and compiling against the Blaze library, the so-called "runtime
#  exception"; see the file COPYING. If not, see http://www.gnu.org/licenses/.
#
#==================================================================================================


# Release information
MAJOR=1
MINOR=4




#==================================================================================================
# Setup of the two release archives
#==================================================================================================

mkdir blaze-$MAJOR.$MINOR
mkdir blaze-docu-$MAJOR.$MINOR
git clone http://code.google.com/p/blaze-lib ./blaze-$MAJOR.$MINOR
cd blaze-$MAJOR.$MINOR
rm -rf .git
find * -type f -iname ".gitignore" -exec rm -f {} \;
./configure
make doc
cp -r doc/html/* ../blaze-docu-$MAJOR.$MINOR
cd ..
tar czf blaze-$MAJOR.$MINOR.tar.gz ./blaze-$MAJOR.$MINOR
tar czf blaze-docu-$MAJOR.$MINOR.tar.gz ./blaze-docu-$MAJOR.$MINOR
rm -rf blaze-$MAJOR.$MINOR blaze-docu-$MAJOR.$MINOR
